CREATE TABLE IF NOT EXISTS guitars (
    id UUID PRIMARY KEY,
    brand VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    strings_count INT NOT NULL,
    is_electric BOOLEAN NOT NULL DEFAULT FALSE
);